services:
  mysql:
    image: mysql:latest
    container_name: pinFoodDbMySql
    environment:
      - MYSQL_ROOT_PASSWORD=Pass123$
      - MYSQL_DATABASE=PinFoodDatabase
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Pass123$
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  
  pinfoodapi:
    container_name: pinFoodApi
    build:
      context: .
      dockerfile: ./PinFood.Api/Dockerfile
    ports:
      - 15000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Port=3306;Database=PinFoodDatabase;Uid=admin;Pwd=Pass123$;
      - FileStorage__StaticFileRequestPath=/files
      - FileStorage__BasePath=/app/files
    volumes:
      - /Users/adamludwiczak/Documents/PinFood:/app/files
        
volumes:
  mysql_data:
